// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAZP87hwimuOUAnvI3DLDElxqy08dqpRI',
    appId: '1:813278783768:web:ad2dbd89e07a42fb08166d',
    messagingSenderId: '813278783768',
    projectId: 'mynote-4f862',
    authDomain: 'mynote-4f862.firebaseapp.com',
    databaseURL: 'https://mynote-4f862-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynote-4f862.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeRyAN08VDt60KizgqHrn2IdhJrbnjcQ8',
    appId: '1:813278783768:android:89efcd4fb6f9d2c608166d',
    messagingSenderId: '813278783768',
    projectId: 'mynote-4f862',
    databaseURL: 'https://mynote-4f862-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynote-4f862.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyHjZG4gnyIaaOJj1BaNIQQI6ARH307s',
    appId: '1:813278783768:ios:c38661e679d834ca08166d',
    messagingSenderId: '813278783768',
    projectId: 'mynote-4f862',
    databaseURL: 'https://mynote-4f862-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynote-4f862.appspot.com',
    iosClientId: '813278783768-0e47f0ee8gojvihb0fjqhqf8n6qqtj91.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyHjZG4gnyIaaOJj1BaNIQQI6ARH307s',
    appId: '1:813278783768:ios:c38661e679d834ca08166d',
    messagingSenderId: '813278783768',
    projectId: 'mynote-4f862',
    databaseURL: 'https://mynote-4f862-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mynote-4f862.appspot.com',
    iosClientId: '813278783768-0e47f0ee8gojvihb0fjqhqf8n6qqtj91.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
